### ISSUE TITLE
Product Requirements for Beckn enabled network observability microsite - MVP-v1

### ISSUE THREAD

**Issue by faizmagic** [beckn/beckn-utilities#110]
Minutes of meeting held for this purpose:

### Description:
This product is designed for the overall monitoring of the Beckn network, with the first milestone focusing **ONLY on OPEN DATA**. Data specific to network participants (useful for troubleshooting, etc.) will not be included in this version.

### Objective:
The primary objective of this product is to establish a robust monitoring framework for the Beckn network, with an initial emphasis on open data. This framework should align with key design principles and be integrated into the Beckn ONIX platform.

### Design Principles:
1. **Interoperability:** Should be compatible with standards like Open Telemetry.
2. **Privacy Compliance:** Must protect Personally Identifiable Information (PII).
3. **Beckn ONIX Integration:** Should be a core component of the Beckn ONIX platform.
4. **Scalability:** Should be scalable to accommodate future network growth.
5. **Spatial and Temporal Scoping:** Should support scoping data spatially and temporally.

### Scope for MVP 1:
1. **Network Participant (NP) Level Data:** Registry lookup information.
2. **Aggregated Transaction Data:** Includes DOFP and Catalog data (No NP-specific data; presented as time series).
3. **Infrastructure SLA Metrics:** Metrics such as availability, health, throughput, error rate, etc.
4. **Downloadable Reports:** Summary reports that can be downloaded.
5. **Alerts:** Notifications when NPs are down.

### Future Scope:
1. **Settlement/Reconciliation Data:** Incorporate data from currently unavailable sources.
2. **Network Participant Endpoint Information:** 'About' endpoint for network participants.
3. **Notification Mechanisms:** Enhanced alerting and notification systems linked to network events.

### Goals:
- [ ] Implement the MVP 1 scope focusing on open data and basic network observability.
- [ ] Ensure the product adheres to the outlined design principles.
- [ ] Successfully integrate the monitoring tool into the Beckn ONIX platform.

### Expected Outcome:
- A fully functional network monitoring tool that provides essential open data insights and alerts, in compliance with the Beckn ONIX platform's design and scalability requirements.

### Acceptance Criteria:
- [ ] Completion of all MVP 1 scope items with verified functionality.
- [ ] Confirmation of adherence to design principles.
- [ ] Successful testing and deployment of the monitoring product within Beckn ONIX.

### Mockups / Wireframes:
NA

### Product Name:
Beckn Network Monitoring Tool

### Domain:
Network Observability

### Tech Skills Needed:
Beckn ONIX, Open Telemetry, L2-config, Data Privacy Compliance

### Complexity:
High

### Category:
Monitoring and Observability

### Sub Category:
Network Infrastructure

**Comment by viraj89** [comment]
Not moving to Aug 19 iteration, will be closed on Aug 19.

**Comment by vbabuEM** [comment]
The requirements are documented here https://fide-official.atlassian.net/wiki/x/A4CtI

**Comment by viraj89** [comment]
The PRD for this MVP version is [here](https://fide-official.atlassian.net/wiki/spaces/BBB/pages/634290177/PRD+for+Network+Observability) on Confluence.

**Comment by viraj89** [comment]
### Status Update


Today, Faiz and I reviewed the FRD document and discussed the functional requirements. 

#### Key Discussion Points:
- During our discussion, it was highlighted that in previous conversations between Faiz and Sujith, the communication between the **Protocol Server** and the **Observability Server** should take place over the **Beckn protocol** rather than using external channels.
- This had been brought up in prior discussions, and further clarification is needed on this point.
- To address this, an email has been sent to **Ravi** and **Faiz** to initiate further discussions.

### Next Steps:
1. Continue discussions with **Ravi** and **Faiz** regarding the communication protocol between the servers.
2. Based on the outcomes of these discussions, we will proceed with starting the **UI/UX wireframes and design work**.

**Comment by viraj89** [comment]
### Update: PRD for Network Observability Platform

Based on the inputs from Faiz, I reached out to Ravi today to request his time for a discussion. Although Ravi is unavailable due to an event on the evening of October 14, he requested the Outcome Visualization and Success Definition for the Network Observability Platform. Also shared the same to Ravi for his initial review.

I worked on this and have updated the PRD with the necessary details.

- **PRD for Network Observability**: The document now includes the Outcome Visualization and Success Definition. You can view the updates here:  
  [PRD for Network Observability](https://fide-official.atlassian.net/wiki/spaces/BBB/pages/634290177/PRD+for+Network+Observability)
