### ISSUE TITLE
Migrate MIT catalogs to BOC environment

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#112]
### Description:
Migrate catalogs created during the MIT mission project to BOC environments in Strapi or Vendure BPP to ensure future readiness. Close AWS instances of MIT mission projects.

### Goals:
- [x] Verify existing schema in Strapi and make necessary changes.
- [x] Identify the number of catalogs.
- [x] Share and discuss with Faiz.
- [ ] Prepare catalogs in CSV format for import.
- [ ] Use the import script to migrate catalogs. [Link to CSV samples](https://github.com/beckn/beckn-utilities/tree/main/strapi-catalog-utility/samples).
- [ ] Move catalogs from MIT to BOC instance.
- [ ] Close the MIT BPP instance.
- [ ] Redeploy Beckn Bot and keep this instance up.

### Expected Outcome:
- Catalogs from MIT mission project are successfully migrated to BOC environments.
- AWS instances of MIT mission projects are closed.
- Beckn Bot is redeployed and functional.

### Acceptance Criteria:
- [ ] Schema in Strapi matches MIT Strapi instance.
- [ ] Number of catalogs identified and shared with Faiz.
- [ ] Catalogs prepared in CSV format.
- [ ] Catalogs imported using the script.
- [ ] Catalogs moved to BOC instance.
- [ ] MIT BPP instance closed.
- [ ] Beckn Bot redeployed successfully and instance kept up.

### Mockups / Wireframes:
NA

### Product Name:
Beckn Protocol ONIX

### Domain:
Infra

### Tech Skills Needed:
Strapi, Vendure, CSV Handling, Scripting, DevOps

### Complexity:
Medium

### Category:
Migration

### Sub Category:
Data Migration

**Comment by shreyvishal** [comment]
Current Status: 
Identified no. of catalogs in each MIT domain instances

MIT Instances:
	Tourism:
		No Of Items: 4
		No of Providers: 4
	Energy:
		No Of Items: 32
		No of Providers: 33
	Retail:
		No Of Items: 52
		No of Providers: 49
	Hotel:
		No Of Items: 41
		No of Providers: 43

Have Taken DB dump for all the database in MIT Instances
But migration to dev is not possible in current scope as migration is causing error because of the conflicts between the databases due to conflict in the tables primary keys.
Have spent above 12 hrs for completing this much work


![Image](https://github.com/user-attachments/assets/6f83bfdb-e1b9-40fd-b8ec-d7226f1dedd0)
