### ISSUE TITLE
/about endpoint for network participants

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#117]
## Description
Following the discussion on September 12 between Venkatesh, Venky, Abhi, and Viraj, the following outcomes were identified. Venkatesh captured these details and shared them via email and on the Confluence page.

### Introduction
In the Beckn network, participants register with the Registry by providing their public URL and keys. This information is essential for communication and message authentication within the network.

However, during transactions, it has been observed that network participants require additional information about counterparties, such as public bank details, KYC information, tax-related details, organizational data, and verifiable credentials.

To avoid inefficiencies stemming from using alternative communication channels (e.g., email, messaging) to gather this information, it is proposed to add an "about" endpoint for each network participant (BAP and BPP). This endpoint would allow participants to publish relevant public information about themselves.

Special thanks to Venkatraman Mahadevan for assisting in constructing this document.

## Goals
- [ ] Implement an "about" endpoint for both BAP and BPP network participants.
- [ ] Ensure that the endpoint allows participants to publish public information, such as bank details, KYC information, tax details, and organizational credentials.
- [ ] Facilitate easy access to counterparties’ public information, improving transaction efficiency within the network.
- [ ] Avoid the need for alternative communication channels (e.g., email, messaging) to gather necessary public details.

## Expected Outcome
- A new "about" endpoint is added to each network participant (BAP and BPP) in the Beckn network.
- Participants can publish relevant public information, accessible by counterparties during transactions.
- The new endpoint eliminates the need for alternative channels to gather essential public details, enhancing transaction efficiency.

## Acceptance Criteria
- [ ] The "about" endpoint is successfully implemented for BAP and BPP participants.
- [ ] The endpoint allows network participants to publish and access public information such as bank details, KYC information, tax details, and organizational credentials.
- [ ] The endpoint is tested and verified to function correctly, improving the transaction process within the network.

## Mockups / Wireframes
NA

## Product Name
Beckn Network

## Domain
Network Communication and Authentication

## Tech Skills Needed
- API Development
- BAP/BPP Knowledge
- Beckn Protocol Understanding

## Complexity
Medium

## Category
API Development

## Sub Category
Network Communication

## Project View
Beckn Network Enhancements

## Project Name
Beckn Network

**Comment by yesrag2309** [comment]
@emmayank - Kindly have a sync up call with venkatramanm @vbabuEM on what needs to do on this ticket. Please update the start & end date after the call.

@viraj89 @faizmagic

**Comment by yesrag2309** [comment]
@emmayank - any update on this ticket? please update

@viraj89 @faizmagic

**Comment by yesrag2309** [comment]
@viraj89 -Need to discuss this card on tomorrows 3pm backlog discussion call.

@emmayank @faizmagic

**Comment by yesrag2309** [comment]
@viraj89 -Need to discuss this card on tomorrows 3pm backlog discussion call.

@emmayank @faizmagic @SyedMubarak008

**Comment by yesrag2309** [comment]
@viraj89 -Can you please update the current status on of this card

@emmayank @faizmagic

**Comment by yesrag2309** [comment]
@viraj89 - Please find below the current week status and next week plan.

Current week status - Discussions have been initiated with Venky and Ravi for further details.
Next week plan - Planning to establish clarity, gather details, and set priorities for the next iteration.

@emmayank @faizmagic

**Comment by viraj89** [comment]
A meeting is scheduled with Venky on Sept 12, 6pm IST to understand further for this ticket. cc - @yesrag2309 @faizmagic @emmayank @vbabuEM

**Comment by viraj89** [comment]
### MOM and Outcome of Discussion with Venky

**Date of Discussion:** September 12, 2024  
**Participants:** Venkatesh, Venky, Abhi, Viraj

The following are the outcomes of the discussion that took place on September 12 between Venkatesh, Venky, Abhi, and Viraj. Venkatesh has captured the details and shared them via email and on the Confluence page [here](https://fide-official.atlassian.net/wiki/spaces/BBB/pages/595984386/Adding+an+about+endpoint+to+Network+Participants).

## Introduction

Within the Beckn network, participants register themselves with the Registry by providing their public URL and keys. This information is crucial for communication and message authentication within the network.

However, in practice, it has been found that Network Participants require additional information about the counterparties during transactions, including but not limited to public bank details, KYC details, tax-related details, organizational information, and verifiable credentials.

To avoid inefficiencies caused by using alternative channels (e.g., email, messaging) to gather this information, it is proposed that an **"about"** endpoint be added to each network participant (BAP and BPP). This will allow the participant to publish public information about itself.

Thanks to Venkatraman Mahadevan for his assistance in constructing this document.

## API Endpoint

- The **about** endpoint will be supported by both BAP and BPP.
- It is **optional**, but network facilitators may mandate it.
- The endpoint will support the **POST** verb to align with other Beckn endpoints, though it may seem like a **GET** operation.
- The output will be a **JSON object** that should be **extensible**.
- The object will include both first-class keys and additional information via the **TagGroup** and **Tags** mechanism.
- **Caching** is currently not defined, so users should not cache the results.

### Data Expected in the Initial Implementation:
- Organization information (KYC details)
- Verifiable credentials
- Payment-related information (bank details, virtual payment ID)
- Subscriber information (subscriber ID, URL, public key)
- Tax-related information (PAN/TAN, GST for India)
- IP address for whitelisting

**Design Notes:**
- Use existing Beckn components wherever possible.
- For missing components, follow similar schema design to align with Beckn's meta API.

## Design Choices and Implications

- The API is implemented independently of Beckn's transaction, meta, and registry APIs.
- Alternative: Including this information in the subscriber data registered with the Registry, though currently this is kept separate.
- No **authentication** requirement for this API, but it could use the same authentication as Beckn requests to prevent DDOS attacks.
- The **about** API is synchronous, unlike most transactional Beckn APIs, which are asynchronous. It could be made asynchronous to handle independent updates to the data.
- Handling changes to published data is an open issue. Currently, caching is not recommended, but frequent non-cached data access may cause a burden on transaction flow.

## Conclusion

This discussion highlighted the requirement for an **about** endpoint to be implemented by BAP and BPP, along with potential design choices and challenges. Further discussions may be needed to finalize the implementation.

**Comment by yesrag2309** [comment]
@vbabuEM - As discussed in today's tech stand-up, please share the prepared document to @ravi-prakash-v we can ask his time for review on call or offline document review by him. Based on his review we can move forward on the development activity or document rework with Hyper Beckn concepts.

@viraj89 @faizmagic @emmayank

**Comment by vbabuEM** [comment]
https://docs.google.com/document/d/1IoO4m5v4zdIkB_naaIWMMSyl2_XnRBeQg6lUV49mr8w/edit?usp=sharing

**Comment by yesrag2309** [comment]
Review request email has been sent to @ravi-prakash-v for the above draft requirement document on 17th Sep 2024

@vbabuEM @faizmagic @viraj89 @emmayank

**Comment by viraj89** [comment]
**Update:**

The `/about` endpoint concept has been renamed to `beckn.json` and is currently under discussion in the working group following the Beckn One workshop on October 30. 
Hence marking this ticket as closed. 

**Relevant Updates:**
- [Issue #282](https://github.com/beckn/beckn-onix/issues/282)
- [Issue #287](https://github.com/beckn/beckn-onix/issues/287)
