### ISSUE TITLE
AWS details requested

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#134]
## Description
Provide details on the current AWS usage, costs, and recommendations for cost optimization. The goal is to establish a new baseline for AWS costs and explore potential savings, particularly through EC2 instance reservation.

## Goals
- [x] Review AWS instances and their current usage.
- [x] Analyze the billing details for July and August 2024.
- [x] Identify the most and least used applications in AWS.
- [x] Discuss the potential for cost reduction by reserving EC2 instances.
- [x] Establish a new baseline for AWS costs.

## Expected Outcome
A clear understanding of the current AWS usage and costs, along with an agreed-upon strategy to manage and potentially reduce AWS expenses. The outcome should include a new baseline for AWS costs and a plan to monitor and manage these costs moving forward.

## Acceptance Criteria
- [x] A detailed review of AWS instances is completed and documented.
- [x] Billing for July and August 2024 is analyzed and summarized.
- [x] Identification of the most and least used AWS services.
- [x] Feasibility of reserving EC2 instances is discussed and documented.
- [x] A new baseline for AWS costs is agreed upon by all stakeholders.
- [x] A plan for ongoing monitoring and alerting on AWS costs is developed.

## Mockups / Wireframes
N/A

## Product Name
Beckn

## Domain
Infra

## Tech Skills Needed
- AWS Management
- Cost Optimization
- Financial Analysis

## Complexity
Medium

## Category
Cost Management

## Sub Category
AWS Usage Optimization

**Comment by prasad-takale-eminds** [comment]
Below are the details requested regarding AWS:

1. **AWS Instances:** 
You can find the list of AWS instances on this [Google Sheet](https://docs.google.com/spreadsheets/d/14rcwtUakinYpf6XfOw83RAnPM1Airnwd/edit?pli=1&gid=39528701#gid=39528701) under the tab "AWS Instances as of August 22, 2024."
2. **Billing for July and August 2024:** 
July 2024: 
![image](https://github.com/user-attachments/assets/a82a9d34-ee29-462a-b4c9-89ea32bbd629) 
August 2024 (as of August 22, 2024): 
![image](https://github.com/user-attachments/assets/2eeae116-14fe-4cb8-b9ba-ea8781aea923)
3. **Billing Breakdown for August 2024:** 
![image](https://github.com/user-attachments/assets/5b753e8b-f552-4f75-a23b-2d6ba763f040)
4. **Most Used Application:** 
Based on the breakdown, EC2 instances account for the majority of the cost. There have been discussions about reserving instances to potentially reduce costs by up to 30%. We can explore this option further, though it would require upfront payment as it’s a prepaid model.
5. **Least Used Application:** 
S3 services appear to be the least costly based on current usage.
6. **Other Services:**
The other services in use are listed in the breakdown above.

**Overall Summary:** Our earlier goal was to keep billing below the USD 2,500 cap that has not been met now due to the increase in instances over the last few months. The current forecast for August 2024 is USD 5,694. We need to establish a new baseline number for monitoring and alerts. We suggest setting up a one- or two-day workshop to review these in detail and identify potential cost-saving opportunities. Please let us know your availability and thoughts.
